# Generated by Django 4.2.20 on 2025-07-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_shipping_address_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal')], default='card', max_length=50),
        ),
    ]
