# Generated by Django 4.2.23 on 2025-08-07 01:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_guest_token_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
